"""
G-code generator for FlashForge Creator 3 Pro output
"""

from pathlib import Path
from .utils import get_logger, ensure_directory

logger = get_logger(__name__)


class GCodeGenerator:
    """Generate printer-ready G-code from adaptive infill geometry."""

    def __init__(self, config):
        self.config = config
        self.nozzle_temp = config['print']['nozzle_temp']
        self.bed_temp = config['print']['bed_temp']
        self.layer_height = config['print']['layer_height']
        self.print_speed = config['print']['print_speed']

    def generate(self, infill_layers, output_path):
        """Generate a full G-code file."""
        ensure_directory(Path(output_path).parent)

        lines = []
        lines.append("; Generated by stress-aware 3D printing project")
        lines.append("; Printer: FlashForge Creator 3 Pro")
        lines.append("M104 S{}".format(self.nozzle_temp))
        lines.append("M140 S{}".format(self.bed_temp))
        lines.append("G28")
        lines.append("G90")
        lines.append("M82")
        lines.append("G1 Z0.2 F1200")
        lines.append("G1 X0 Y0 F1200")

        for idx, layer in enumerate(infill_layers):
            z = layer['z']
            lines.append(f"; LAYER {idx+1} Z{z:.3f}")
            lines.append(f"G1 Z{z:.3f} F1200")
            for command in layer.get('gcode_commands', []):
                lines.append(command)

        lines.append("M104 S0")
        lines.append("M140 S0")
        lines.append("M84")

        output_file = Path(output_path)
        output_file.write_text("\n".join(lines) + "\n")
        logger.info(f"G-code written to {output_path}")

        return output_file

    def build_layer_commands(self, infill_layers):
        """Build G1 commands for each layer from layer data."""
        for layer in infill_layers:
            commands = []
            for line in layer['lines']:
                if len(line) == 0:
                    continue
                start = line[0]
                end = line[-1]
                commands.append(f"G1 X{start[0]:.3f} Y{start[1]:.3f} Z{start[2]:.3f} F{self.print_speed * 60:.1f}")
                commands.append(f"G1 X{end[0]:.3f} Y{end[1]:.3f} Z{start[2]:.3f} E0.8 F{int(self.print_speed * 60)}")
            layer['gcode_commands'] = commands
        return infill_layers
